package balik;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NewNotebook
 */

import java.util.*;
import javax.swing.JOptionPane;  //na message okno
import javax.swing.JFileChooser;
import java.io.File;

public class oknoGenerovaniSkriptu extends javax.swing.JFrame {
    List<String> hodnotyProUpdate = new ArrayList<String>(); //list, do ktereho se ukladaji honodty nastavovane updatem; index hodnoty odpovida indexu prislusneho sloupce v listu sloupceVDotazu
    List<String> podminkyVDotazu = new ArrayList<String>(); //list, do ktereho se ukladaji cele podminky za WHERE
    List<nactenaTabulka> listTabulek = new ArrayList<nactenaTabulka>();  //list tabulek, ktere do dotazu pridavame
    dotaz prvniDotaz = new dotaz();
    nactenaDatabaze datab = new nactenaDatabaze();
    /**
     * Creates new form oknoGenerovaniSkriptu
     */
    public oknoGenerovaniSkriptu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgVyberTypuDotazu = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        vyslednySkript = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbSelect = new javax.swing.JRadioButton();
        rbUpdate = new javax.swing.JRadioButton();
        rbDelete = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labJmenoDatabaze = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbJmenoTabulky = new javax.swing.JComboBox<>();
        panelPodminky = new javax.swing.JPanel();
        butPridejPodminku = new javax.swing.JButton();
        cbSloupecVPodmince = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbTypPorovnani = new javax.swing.JComboBox<>();
        tbPorovnavanaHodnota = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        butPridaniSloupce = new javax.swing.JButton();
        cbSloupceTabulky = new javax.swing.JComboBox<>();
        tfProUpdate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        butOdebraniSloupce = new javax.swing.JButton();
        cbOdebraniSloupce = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        cbSloupecVOdebraniPodminky = new javax.swing.JComboBox<>();
        butOdeberPodminku = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpAliasTabulky = new javax.swing.JTextPane();
        butPridejTabulku = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbTypSpojeniTabulek = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbSpojovaneTab = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbLevaTabulka = new javax.swing.JComboBox<>();
        cbPorovnaniTabulek = new javax.swing.JComboBox<>();
        cbPravaTabulka = new javax.swing.JComboBox<>();
        butSpojeniTabulek = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generování SQL dotazů - v0.2");

        vyslednySkript.setEditable(false);
        vyslednySkript.setColumns(20);
        vyslednySkript.setRows(5);
        jScrollPane1.setViewportView(vyslednySkript);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Typ dotazu:");

        bgVyberTypuDotazu.add(rbSelect);
        rbSelect.setSelected(true);
        rbSelect.setText("SELECT");
        rbSelect.setEnabled(false);
        rbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelectActionPerformed(evt);
            }
        });

        bgVyberTypuDotazu.add(rbUpdate);
        rbUpdate.setText("UPDATE");
        rbUpdate.setEnabled(false);
        rbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUpdateActionPerformed(evt);
            }
        });

        bgVyberTypuDotazu.add(rbDelete);
        rbDelete.setText("DELETE");
        rbDelete.setEnabled(false);
        rbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(rbSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDelete)
                .addContainerGap(1025, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbSelect)
                    .addComponent(rbUpdate)
                    .addComponent(rbDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Databáze");

        jButton1.setText("Nacteni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labJmenoDatabaze.setText("Zatím nezadána");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(labJmenoDatabaze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(labJmenoDatabaze))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Tabulka");

        cbJmenoTabulky.setEnabled(false);

        panelPodminky.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        butPridejPodminku.setText("Přidat podmínku");
        butPridejPodminku.setEnabled(false);
        butPridejPodminku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPridejPodminkuActionPerformed(evt);
            }
        });

        cbSloupecVPodmince.setEnabled(false);

        jLabel4.setText("Sloupec");

        cbTypPorovnani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "<=", ">=" }));
        cbTypPorovnani.setEnabled(false);

        tbPorovnavanaHodnota.setText("hodnota");
        tbPorovnavanaHodnota.setEnabled(false);

        javax.swing.GroupLayout panelPodminkyLayout = new javax.swing.GroupLayout(panelPodminky);
        panelPodminky.setLayout(panelPodminkyLayout);
        panelPodminkyLayout.setHorizontalGroup(
            panelPodminkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPodminkyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSloupecVPodmince, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTypPorovnani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbPorovnavanaHodnota, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPodminkyLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(butPridejPodminku)
                .addGap(124, 124, 124))
        );
        panelPodminkyLayout.setVerticalGroup(
            panelPodminkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPodminkyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPodminkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSloupecVPodmince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbTypPorovnani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbPorovnavanaHodnota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butPridejPodminku)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        butPridaniSloupce.setText("Přidáni sloupce do dotazu");
        butPridaniSloupce.setEnabled(false);
        butPridaniSloupce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPridaniSloupceActionPerformed(evt);
            }
        });

        cbSloupceTabulky.setEnabled(false);

        tfProUpdate.setText("Hodnota sloupce pro update");
        tfProUpdate.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSloupceTabulky, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(butPridaniSloupce))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfProUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cbSloupceTabulky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfProUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butPridaniSloupce)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        butOdebraniSloupce.setText("Odebraní sloupce v dotazu");
        butOdebraniSloupce.setEnabled(false);
        butOdebraniSloupce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOdebraniSloupceActionPerformed(evt);
            }
        });

        cbOdebraniSloupce.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbOdebraniSloupce, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(butOdebraniSloupce)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbOdebraniSloupce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(butOdebraniSloupce)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbSloupecVOdebraniPodminky.setEnabled(false);

        butOdeberPodminku.setText("Odebrat podmínku");
        butOdeberPodminku.setEnabled(false);
        butOdeberPodminku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOdeberPodminkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbSloupecVOdebraniPodminky, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(butOdeberPodminku)
                .addGap(117, 117, 117))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbSloupecVOdebraniPodminky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butOdeberPodminku))
        );

        jLabel3.setText("Alias tabulky");

        tpAliasTabulky.setEnabled(false);
        jScrollPane2.setViewportView(tpAliasTabulky);

        butPridejTabulku.setText("Přidej tabulku do dotazu");
        butPridejTabulku.setEnabled(false);
        butPridejTabulku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPridejTabulkuActionPerformed(evt);
            }
        });

        jLabel6.setText("Typ spojení tabulek:");

        cbTypSpojeniTabulek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "FULL OUTER JOIN" }));
        cbTypSpojeniTabulek.setEnabled(false);

        jLabel7.setText("Spojované tabulky:");

        cbSpojovaneTab.setEnabled(false);
        cbSpojovaneTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpojovaneTabActionPerformed(evt);
            }
        });

        jLabel8.setText("Spojovací podmínka:");

        cbLevaTabulka.setEnabled(false);

        cbPorovnaniTabulek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=" }));
        cbPorovnaniTabulek.setEnabled(false);

        cbPravaTabulka.setEnabled(false);

        butSpojeniTabulek.setText("Přidat podmínku spojení");
        butSpojeniTabulek.setEnabled(false);
        butSpojeniTabulek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSpojeniTabulekActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Místo pro GROUP BY, HAVING a ORDER BY");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTypSpojeniTabulek, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSpojovaneTab, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLevaTabulka, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(butSpojeniTabulek)
                                        .addGap(249, 249, 249))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbJmenoTabulky, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(43, 43, 43)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(butPridejTabulku)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(cbPorovnaniTabulek, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbPravaTabulka, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPodminky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbJmenoTabulky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPridejTabulku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbLevaTabulka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPorovnaniTabulek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPravaTabulka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbTypSpojeniTabulek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbSpojovaneTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSpojeniTabulek)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(panelPodminky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    public void zmenaTypuDotazu(){
        //vola se po zmene prepinace SELECT/UPDATE/DELETE
        podminkyVDotazu.removeAll(podminkyVDotazu);      //vyprazdnuje list s podminkami za WHERE
        vyslednySkript.setText("");                      //vyprazdnuje okno s predchozim textem skriptu 
        cbOdebraniSloupce.removeAllItems();              //vyprazdnuje obsah comboboxu s jmeny sloupcu
        cbSloupceTabulky.removeAllItems();
        cbSloupecVPodmince.removeAllItems();
        cbSloupecVOdebraniPodminky.removeAllItems();     //vyprazdnuje obsah comboboxu s podminkami za WHERE
        listTabulek.clear();
        

        //nastavuje se parametr dotazu (S, U nebo D) a enabluji/disabluji se pro dany typ dotazu nepotrebne prvky v uzivatelskem rozhrani        
        if(rbUpdate.isSelected() == true){
            tfProUpdate.setEnabled(true);
            butPridaniSloupce.setEnabled(true);
            prvniDotaz.zmenTypDotazu('U');
        }
        else if(rbSelect.isSelected() == true){
            tfProUpdate.setEnabled(false);
            butPridaniSloupce.setEnabled(true);
            prvniDotaz.zmenTypDotazu('S');
        }
        else if(rbDelete.isSelected() == true){
            tfProUpdate.setEnabled(false);
            butPridaniSloupce.setEnabled(false);
            cbSloupceTabulky.setEnabled(false);
            butPridaniSloupce.setEnabled(false);
            prvniDotaz.zmenTypDotazu('D');
        }
        
        butOdebraniSloupce.setEnabled(false);            //diabluje button odebirajici sloupce - combobox by mel byt prazdny a tak by kliknuti jen generovalo chybu
        butOdeberPodminku.setEnabled(false);             //disabluje button odebirajici podminky - jelikoz neni co odebrat, jen by kliknuti na nej hazelo errory
        prvniDotaz.vymazVse();
        butPridejTabulku.setEnabled(true);
        cbTypSpojeniTabulek.setEnabled(false);
        cbSpojovaneTab.setEnabled(false);
        cbLevaTabulka.setEnabled(false);
        cbPorovnaniTabulek.setEnabled(false);
        cbPravaTabulka.setEnabled(false);
        butSpojeniTabulek.setEnabled(false);
        butPridaniSloupce.setEnabled(false);
        cbSloupceTabulky.setEnabled(false);
        tfProUpdate.setEnabled(false);
        butPridaniSloupce.setEnabled(false);
        cbOdebraniSloupce.setEnabled(false);
    }
    
    public void zmenaDotazu(){
        //vola se pri zmene typu dotazu, pri pridani ci odebrani sloupce.. prakticky furt
        vyslednySkript.setText(prvniDotaz.vygenerujTextDotazu(listTabulek)); //naplni se textove pole s podobou dotazu 
    }
   
    public void nacteni(String adresa){
        //vola se pri stisknuti tlacitka nacteni, tj. asi jen jednou behem behu progrmau
        datab.nactiDatabaze(adresa);                          //otevre se databaze
        List<String> tabulkyVDat = datab.dejTabulkyVDatabazi();      //a naplni se list se seznamem tabulek v ni
        for(String element : tabulkyVDat) {                          //pro kazdy element typu string z listu tabulkyVDat
            cbJmenoTabulky.addItem(element.toString());              //se tento element vlozi do comboboxu obsahujici jmena tabulek
        }
    }
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String adresaSouboru = "";
        String kratkeJmenoDatabaze = "";
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir")); //aby se openFile dialog oteviral v pracovnim adresari programu
         if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
         File file = fileChooser.getSelectedFile();
         adresaSouboru = file.toString();
        }
        nacteni(adresaSouboru);
        kratkeJmenoDatabaze = adresaSouboru.substring(adresaSouboru.lastIndexOf('\\') + 1);
        prvniDotaz.nastavJmenoDatabaze(kratkeJmenoDatabaze);
        labJmenoDatabaze.setText(adresaSouboru);
        cbJmenoTabulky.setEnabled(true);
        tpAliasTabulky.setEnabled(true);
        butPridejTabulku.setEnabled(true);
        rbSelect.setEnabled(true);
        rbUpdate.setEnabled(true);
        rbDelete.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butPridaniSloupceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPridaniSloupceActionPerformed
        //vola se po stisknnuti tlacitka pridat sloupec
        String aliasPlusSloupec = cbSloupceTabulky.getSelectedItem().toString();  //vezme aktivni prvke v comboboxu
        String jenomSloupec = "";
        String aliasTabulky = "";
        String jmenoTabulky = "";
        if( aliasPlusSloupec.length() >= 5 && aliasPlusSloupec.charAt(4) == '.'){  //z standardnich okolnosti by prvek v comboboxu mel byt ve tvaru alias.sloupec
            jenomSloupec = aliasPlusSloupec.substring(5);                          //rozdeleni elementu comboboxu na alias a sloupec
            aliasTabulky = aliasPlusSloupec.substring(0,4);
        }
        else{                                                                      //takze by se else nemelo vubec volat
            jenomSloupec = aliasPlusSloupec;
            aliasTabulky = "";
        }
       
        for(nactenaTabulka element : listTabulek) {                             //jmeno tabulky v comboboxu neni, takze se musime podivat do listu obsahujici tabulky a podle alias upotrebnou tabulku najit
            if(aliasTabulky.equals(element.dejAlias())){
                jmenoTabulky = element.dejJmenoTabulky();
            }
        }
        prvniDotaz.pridejSloupecDoDotazu(jenomSloupec, aliasTabulky, jmenoTabulky, tfProUpdate.getText());  //zporstredkovane se vytvori novy sloupecVDotazu
        cbOdebraniSloupce.addItem(cbSloupceTabulky.getSelectedItem().toString());    //prida se prvek do comboboxu na vyrazovani sloupcu
        hodnotyProUpdate.add(tfProUpdate.getText());
        butOdebraniSloupce.setEnabled(true);                                        //enabluje se cudlik na odebirani sloupcu
        cbOdebraniSloupce.setEnabled(true);
        zmenaDotazu();
    }//GEN-LAST:event_butPridaniSloupceActionPerformed

    private void rbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUpdateActionPerformed
        zmenaTypuDotazu();
        
    }//GEN-LAST:event_rbUpdateActionPerformed

    private void rbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSelectActionPerformed
        zmenaTypuDotazu();
    }//GEN-LAST:event_rbSelectActionPerformed

    private void rbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDeleteActionPerformed
        zmenaTypuDotazu();
        zmenaDotazu();
    }//GEN-LAST:event_rbDeleteActionPerformed

    private void butOdeberPodminkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOdeberPodminkuActionPerformed
        podminkyVDotazu.remove(cbSloupecVOdebraniPodminky.getSelectedItem().toString());
        prvniDotaz.odeberPodminkuVDotazu(cbSloupecVOdebraniPodminky.getSelectedItem().toString());
        cbSloupecVOdebraniPodminky.removeItem(cbSloupecVOdebraniPodminky.getSelectedItem());
        if( podminkyVDotazu.size() == 0){
            cbSloupecVOdebraniPodminky.setEnabled(false);
            butOdeberPodminku.setEnabled(false);
        }
        
        zmenaDotazu();
    }//GEN-LAST:event_butOdeberPodminkuActionPerformed

    private void butOdebraniSloupceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOdebraniSloupceActionPerformed
        //vola se po zmacknuti tlacitka na odebrani sloupce
        String sloupecKOdebrani = cbOdebraniSloupce.getSelectedItem().toString();
        prvniDotaz.odeberSloupecDotazu(sloupecKOdebrani);                           //sloupec se odebere z dotazu
        cbOdebraniSloupce.removeItem(cbOdebraniSloupce.getSelectedItem());          //odebrany sloupec se odebere z odebiraciho comboboxu
        if( prvniDotaz.sloupce2.size() == 0) {
            cbOdebraniSloupce.setEnabled(false);
            butOdebraniSloupce.setEnabled(false);                                      //pokud uz neni zadny sloupec, ktery by se mohl odebrat, odebiraci tlacitko se disabluje
        }  
        zmenaDotazu();
    }//GEN-LAST:event_butOdebraniSloupceActionPerformed

    private void butPridejPodminkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPridejPodminkuActionPerformed
        String podminka = cbSloupecVPodmince.getSelectedItem().toString() + " " + cbTypPorovnani.getSelectedItem().toString() + " '" + tbPorovnavanaHodnota.getText() + "'";
        prvniDotaz.pridejPodminkuVDotazu(podminka);
        podminkyVDotazu.add(podminka);
        cbSloupecVOdebraniPodminky.addItem(podminka);
        butOdeberPodminku.setEnabled(true);
        cbSloupecVOdebraniPodminky.setEnabled(true);
        zmenaDotazu();
    }//GEN-LAST:event_butPridejPodminkuActionPerformed

    private void butPridejTabulkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPridejTabulkuActionPerformed
        //vola se po zmacknuti tlacitka pridat tabulku

        
        String jmenoTabulky = cbJmenoTabulky.getSelectedItem().toString();      //prectou se prvky z comboboxu a textfieldu
        String alias = tpAliasTabulky.getText();
        
        if ( (alias.length() == 3) && (Character.isDigit(alias.charAt(2)) == true) && (Character.isLowerCase(alias.charAt(0)) == true) && (Character.isLowerCase(alias.charAt(1)) == true)  ){
            //pokud je podminka splnena, updatuje se skript o alias
            cbSloupceTabulky.setEnabled(true);          //enabluje se hromada prkvu; disablovane byli kvuli tomu, aby na ne uzivatel neklikl drive, nez se nacte databaze
            butPridaniSloupce.setEnabled(true);
            cbSloupecVPodmince.setEnabled(true);
            cbTypPorovnani.setEnabled(true);
            tbPorovnavanaHodnota.setEnabled(true);
            butPridejPodminku.setEnabled(true);
            cbSloupceTabulky.setEnabled(true);
            
            nactenaTabulka nacTabulka = new nactenaTabulka();                              //vytvori se novy objekt typu nactenaTabulka
            nacTabulka.nactiTabulku(datab.dlouheJmenoDatab, datab.kratkeJmenoDatab, jmenoTabulky, tpAliasTabulky.getText()); //z databaze se nacte tabulka i s jmeny svych sloupcu
            for (int i = 0; i < nacTabulka.dejSeznamSloupcu().size(); i++ ) {  //na pridani sloupcu tabulky do comboboxu
                cbSloupceTabulky.addItem(nacTabulka.alias + "." + nacTabulka.dejSeznamSloupcu().get(i)); //naplni se comboboxy na sloupce v dotazu
                cbSloupecVPodmince.addItem(nacTabulka.alias + "." + nacTabulka.dejSeznamSloupcu().get(i)); //na podminky v dotazu (to za WHERE)
                cbSloupecVPodmince.removeItem(nacTabulka.alias + ".*");                                     //a z podminkoveho comboboxu se odstrani alias.*
                if(prvniDotaz.dejTypDotazu() == 'U') cbSloupceTabulky.removeItem(nacTabulka.alias + ".*"); 
            }
            this.listTabulek.add(nacTabulka);                                   //do senzamu v dotazu pouzitych tabulek se prida nactena tabulka
            
            //cast kodu pro pripravu JOINy tabulek
            if(this.listTabulek.size() > 1 ){
                String staraTabulka = "";                                       //inicializace
                String novaTabulka = "";
                String spojeni = "";
                boolean naplneno = false;
                prvniDotaz.vymazSeznamSpojeni();  //aby se v seznamu spojeni s kazdou pridanou tabulkou a volanim teto funkce nepridavaly duplicicty
                for(nactenaTabulka element : listTabulek) { 
                    if (naplneno == false){   //pokud se nacita prvni tabulka, musi byt postup trochu jiny
                        naplneno = true;        //zapezpeci, aby se tato vetev volala jen jednou
                        novaTabulka = element.dejJmenoTabulky() + " " + element.dejAlias();
                       
                    }
                    else {
                        staraTabulka = novaTabulka;
                        novaTabulka = element.dejJmenoTabulky() + " " + element.dejAlias();
                        spojeni = staraTabulka + " a " + novaTabulka;
                        cbTypSpojeniTabulek.setEnabled(true);
                        cbSpojovaneTab.setEnabled(true);
                        cbLevaTabulka.setEnabled(true);
                        cbPorovnaniTabulek.setEnabled(true);
                        cbPravaTabulka.setEnabled(true);
                        butSpojeniTabulek.setEnabled(true);
                        prvniDotaz.pridejDoSeznamuSpojeni(spojeni);             //a do objektu dotazu se prida nove spojeni tabulek
                    }
                }
                cbSpojovaneTab.removeAllItems();                                //vycisti se combobox
                for(String element2 : prvniDotaz.dejSeznamSpojeni() ) {         //a nakliji se do nej vsechna spojeni
                            cbSpojovaneTab.addItem(element2);
                }
                
                //zajisti, aby byl pocet prvku v lsitech typSpojeni a podminkaSPojeni stejny jako je pocet prvku v cbSpojovaneTab
                while(prvniDotaz.dejSeznamSpojeni().size() > prvniDotaz.dejPodminkySpojeni().size() ){
                    prvniDotaz.pridejPodminkuSpojeni("");
                    prvniDotaz.pridejTypSpojeni("");
                }
            }
            if(prvniDotaz.dejTypDotazu() != 'S'){ //pokud nemame SELECT dotaz, tak se po prvnim pridani tabulky pridavaci tlacitko vypne
                butPridejTabulku.setEnabled(false);
            }
            if(prvniDotaz.dejTypDotazu() == 'D'){ //a pokud mam DELETE dotaz, tak by se vypne i tlacitko pro pridavani sloupcu
                cbSloupceTabulky.setEnabled(false);
                butPridaniSloupce.setEnabled(false);
            }
            zmenaDotazu();  //musi byt na konci funkce, aby se mohly eflektovat vsechny zmeny a nehazel se errror na preteceny index
        }
        else{ //pokud podminka splnena neni, objevi se alert okno a obsah textoveho pole se vymaze
        JOptionPane.showMessageDialog(null, "Byl zadán nevyhovující alias tabulky; nyní podporovaný formát jsou dvě malá písmena následovaná jednou číslicí.", "Špatné zadání aliasu" , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_butPridejTabulkuActionPerformed

    public void naplnComboboxySpojeniSloupcu(String tabulka1, String alias1, String tabulka2, String alias2){
        cbLevaTabulka.removeAllItems();             //vycisti se comboboxy
        cbPravaTabulka.removeAllItems();
        for(nactenaTabulka element : listTabulek) {   //ctou se nactene tabulky
            if (element.dejJmenoTabulky().equals(tabulka1) && element.dejAlias().equals(alias1)){ //a pokud se shoduje jmeno a alias tabulky s tim, co je v comboboxu
                for(String sloupecL: element.dejSeznamSloupcu()){ //tak se sloupce tabulky naliji do comboboxu s podminkami spojeni
                    if(sloupecL != "*"){  //s vyjimkou hvezdicky
                        cbLevaTabulka.addItem(alias1 + "." + sloupecL);
                    }
                }
            }
            if (element.dejJmenoTabulky().equals(tabulka2) && element.dejAlias().equals(alias2)){ //a to same i pro druhou tabulku ve spojeni
                for(String sloupecP: element.dejSeznamSloupcu()){
                    if(sloupecP != "*"){
                        cbPravaTabulka.addItem(alias2 + "." + sloupecP);
                    }
                }
            }
        }  //toto je konec foru nacitajici tabulky
    }
    
    public void nastavPodminkySpojeni(){
        int indexPraveVybranehoSpojeni = cbSpojovaneTab.getSelectedIndex();
        prvniDotaz.nastavTypSpojeni(cbTypSpojeniTabulek.getSelectedItem().toString(), indexPraveVybranehoSpojeni);
        prvniDotaz.nastavPodminkuSpojeni(cbLevaTabulka.getSelectedItem().toString() + " " + cbPorovnaniTabulek.getSelectedItem().toString() + " " + cbPravaTabulka.getSelectedItem().toString(), indexPraveVybranehoSpojeni);
    }
    private void butSpojeniTabulekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSpojeniTabulekActionPerformed
       nastavPodminkySpojeni();
       zmenaDotazu();
    }//GEN-LAST:event_butSpojeniTabulekActionPerformed

    private void cbSpojovaneTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpojovaneTabActionPerformed
        if (cbSpojovaneTab.getItemCount() > 0){
        String celkovyCombobox = cbSpojovaneTab.getSelectedItem().toString();          //vezme se aktualne vybrany prvek v comboboxu spojovanych tabulek 
        
        int prvniMezera = celkovyCombobox.indexOf(" ", 0);                            //a vypraparuji se z nej tabulky a aliasy na zaklade mezer
        int druhaMezera = celkovyCombobox.indexOf(" ", prvniMezera+1);
        int tretiMezera = celkovyCombobox.indexOf(" ", druhaMezera+1);
        int ctvrtaMezera = celkovyCombobox.indexOf(" ", tretiMezera+1);
        
        String prvniTabulka = celkovyCombobox.substring(0, prvniMezera);
        String prvniAlias = celkovyCombobox.substring(prvniMezera + 1, druhaMezera);
        String druhaTabulka = celkovyCombobox.substring(tretiMezera + 1, ctvrtaMezera);
        String druhyAlias = celkovyCombobox.substring(ctvrtaMezera+1);
        
        naplnComboboxySpojeniSloupcu(prvniTabulka, prvniAlias, druhaTabulka, druhyAlias);
        }
    }//GEN-LAST:event_cbSpojovaneTabActionPerformed

     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oknoGenerovaniSkriptu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oknoGenerovaniSkriptu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oknoGenerovaniSkriptu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oknoGenerovaniSkriptu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oknoGenerovaniSkriptu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgVyberTypuDotazu;
    private javax.swing.JButton butOdeberPodminku;
    private javax.swing.JButton butOdebraniSloupce;
    private javax.swing.JButton butPridaniSloupce;
    private javax.swing.JButton butPridejPodminku;
    private javax.swing.JButton butPridejTabulku;
    private javax.swing.JButton butSpojeniTabulek;
    private javax.swing.JComboBox<String> cbJmenoTabulky;
    private javax.swing.JComboBox<String> cbLevaTabulka;
    private javax.swing.JComboBox<String> cbOdebraniSloupce;
    private javax.swing.JComboBox<String> cbPorovnaniTabulek;
    private javax.swing.JComboBox<String> cbPravaTabulka;
    private javax.swing.JComboBox<String> cbSloupceTabulky;
    private javax.swing.JComboBox<String> cbSloupecVOdebraniPodminky;
    private javax.swing.JComboBox<String> cbSloupecVPodmince;
    private javax.swing.JComboBox<String> cbSpojovaneTab;
    private javax.swing.JComboBox<String> cbTypPorovnani;
    private javax.swing.JComboBox<String> cbTypSpojeniTabulek;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labJmenoDatabaze;
    private javax.swing.JPanel panelPodminky;
    private javax.swing.JRadioButton rbDelete;
    private javax.swing.JRadioButton rbSelect;
    private javax.swing.JRadioButton rbUpdate;
    private javax.swing.JTextField tbPorovnavanaHodnota;
    private javax.swing.JTextField tfProUpdate;
    private javax.swing.JTextPane tpAliasTabulky;
    private javax.swing.JTextArea vyslednySkript;
    // End of variables declaration//GEN-END:variables
}
